# Generated by Django 5.1.3 on 2024-11-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles assigned to the user.', related_name='users', to='accounts.role', verbose_name='roles'),
        ),
    ]
